[ingot]
name = "quad_atlas_explorer"
version = "0.1.0"
[dependencies]
core = true
std = true
fmath = true
quilting_atlas = true
quilting_atlas_webgpu = true
quilting_domain = true
quilting_oklch = { path = "../../color/quilting_oklch" }
