[ingot]
name = "classic_quilting_oracle"
version = "0.1.0"

[dependencies]
core = true
quilting_cga = true
quilting_domain = true
quilting_clifford_bezier = true
quilting_patch = true
quilting_quaternion = true
quilting_qb = true
