[package]
name = "quilting-renderer"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "glow-based WebGL2/OpenGL renderer for quilting QB surfaces"

[dependencies]
glow = "0.16"
quilting-core = { version = "0.1.0", path = "../quilting-core" }
quilting-mesh = { version = "0.1.0", path = "../quilting-mesh" }
quilting-shaders = { version = "0.1.0", path = "../quilting-shaders" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["console", "ImageBitmap"] }
