[ingot]
name = "exact_patch_subdivision"
version = "0.1.0"

[dependencies]
core = true
std = true
fmath = true
quilting_clifford_bezier = true
quilting_demo_view = true
quilting_domain = true
quilting_oklch = true
quilting_patch = true
quilting_patch_view = true
quilting_qb = true
quilting_atlas = true
classic_quilting_lod = { path = "../classic_quilting_lod" }
