//! Möbius `c`-parameter estimation — the fitter on the live curved product path.
//!
//! This is the only QB-patch fitter that `remesh_simplified_curved` uses. Given a
//! flat control triangle and a cloud of original-mesh samples that project into
//! it, it recovers a single quaternion `c` describing how the patch bends, and
//! turns that into the three QB weights.
//!
//! Restricting the search to one quaternion (4 DOF) rather than two free weights
//! (8 DOF) is what makes the fit stable enough to ship: the weight parametrization
//! has a null direction along the gauge, and unconstrained Gauss-Newton on it
//! happily walks the denominator `Σλᵢwᵢ` through zero.

use quilting_core::patch::QBTriPatch;
use quilting_core::quaternion::Quat;

use crate::linalg::solve_gauss;

/// Tuning for [`estimate_c_parameter`].
#[derive(Debug, Clone)]
pub struct CEstimatorConfig {
    /// Relative weight of the normal residuals against the position residuals.
    ///
    /// Read once per solve and used for BOTH the residual vector and the
    /// finite-difference Jacobian. If the two ever disagree, Gauss-Newton
    /// descends a different function than the one it measures.
    pub normal_weight: f64,
    /// Tikhonov penalty on |c|², damping overshoot on noisy projected samples.
    ///
    /// Keep this strictly positive. As |c| → ∞ the gauge-normalized weights tend
    /// to `wᵢ → (c Pᵢ)(c P₀)⁻¹`, a limit the surface approaches only slowly, so
    /// the objective has a long flat valley out at large |c|. With the penalty at
    /// exactly zero the solve happily walks into it: on an exactly representable
    /// patch it will return |c| ~ 10⁴ and a *worse* surface than a well-damped
    /// solve returns at the true c. See `test_recovers_known_c`.
    pub regularization: f64,
    /// Maximum Gauss-Newton iterations.
    pub max_iterations: usize,
    /// Finite-difference step used to build the Jacobian.
    pub fd_step: f64,
    /// Stop once the parameter update falls below this norm.
    pub convergence_tol: f64,
}

impl Default for CEstimatorConfig {
    fn default() -> Self {
        Self {
            normal_weight: 0.1,
            regularization: 0.01,
            max_iterations: 100,
            fd_step: 1e-6,
            convergence_tol: 1e-10,
        }
    }
}

/// Estimate the Möbius `c` parameter from mesh samples.
///
/// The QB formula with weights `wᵢ = c*pᵢ_flat + 1` (gauge d=1) produces:
///   X(λ) = (Σ λᵢ Pᵢ (c*Fᵢ+1)) (Σ λᵢ (c*Fᵢ+1))⁻¹
///
/// where Pᵢ are curved corner positions and Fᵢ are flat corner positions.
/// The flat corners serve as a reference: they define where the surface
/// WOULD be if it were flat (c=0).
///
/// For a general mesh patch (not generated by Möbius), we don't have flat corners.
/// But we can use the control triangle (the flat triangle through the 3 corner
/// positions) as the reference. The "flat corners" ARE the curved corners in this case.
///
/// So we solve for c in: wᵢ = c*Pᵢ + 1 (where Pᵢ are the control points),
/// minimizing the QB surface error against sample points.
pub fn estimate_c_parameter(
    control_points: &[[f64; 3]; 3],
    samples: &[[f64; 3]],
    sample_bary: &[[f64; 3]],
    sample_normals: &[[f64; 3]],
    config: &CEstimatorConfig,
) -> Quat {
    let cp = [
        Quat::from_point(control_points[0][0], control_points[0][1], control_points[0][2]),
        Quat::from_point(control_points[1][0], control_points[1][1], control_points[1][2]),
        Quat::from_point(control_points[2][0], control_points[2][1], control_points[2][2]),
    ];

    // Optimize c (4 parameters) to minimize position + normal error.
    // Use regularization to prevent overshoot on noisy/projected data.
    let mut c = Quat::ZERO;
    let eps = config.fd_step;
    let c_reg = config.regularization;
    // Single source of truth: the residual vector below and the finite-difference
    // Jacobian must be built against the same normal weighting.
    let nw = config.normal_weight;

    for _iter in 0..config.max_iterations {
        let mut residuals = Vec::new();
        let weights = make_weights_from_c(c, &cp);
        let patch = QBTriPatch::new(cp, weights);

        for (k, bary) in sample_bary.iter().enumerate() {
            let eval = patch.eval_with_normal(bary[1], bary[2]);
            residuals.push(samples[k][0] - eval.position[0]);
            residuals.push(samples[k][1] - eval.position[1]);
            residuals.push(samples[k][2] - eval.position[2]);
            residuals.push(nw * (sample_normals[k][0] - eval.normal[0]));
            residuals.push(nw * (sample_normals[k][1] - eval.normal[1]));
            residuals.push(nw * (sample_normals[k][2] - eval.normal[2]));
        }

        let nr = residuals.len();

        // Jacobian: 4 columns, nr rows
        let mut jac = vec![vec![0.0; 4]; nr];
        for dim in 0..4 {
            let mut c_plus = c;
            match dim { 0 => c_plus.w += eps, 1 => c_plus.x += eps, 2 => c_plus.y += eps, _ => c_plus.z += eps }
            let w_plus = make_weights_from_c(c_plus, &cp);
            let patch_plus = QBTriPatch::new(cp, w_plus);

            let mut ri = 0;
            for (k, bary) in sample_bary.iter().enumerate() {
                let eval = patch_plus.eval_with_normal(bary[1], bary[2]);
                let r_pos = [samples[k][0] - eval.position[0], samples[k][1] - eval.position[1], samples[k][2] - eval.position[2]];
                let r_norm = [nw * (sample_normals[k][0] - eval.normal[0]), nw * (sample_normals[k][1] - eval.normal[1]), nw * (sample_normals[k][2] - eval.normal[2])];
                for &r in r_pos.iter().chain(r_norm.iter()) {
                    jac[ri][dim] = (r - residuals[ri]) / eps;
                    ri += 1;
                }
            }
        }

        // Normal equations: 4x4
        let mut jtj = [[0.0f64; 4]; 4];
        let mut jtr = [0.0f64; 4];
        for r in 0..nr {
            for i in 0..4 {
                jtr[i] -= jac[r][i] * residuals[r];
                for j in 0..4 {
                    jtj[i][j] += jac[r][i] * jac[r][j];
                }
            }
        }

        // Regularization: penalize |c|² to prevent overshoot
        let c_vals = [c.w, c.x, c.y, c.z];
        for i in 0..4 {
            jtr[i] -= c_reg * c_vals[i];
            jtj[i][i] += c_reg;
        }

        // LM damping
        for i in 0..4 { jtj[i][i] += 1e-6 * (jtj[i][i] + 1e-8); }

        let delta = solve_gauss(jtj, jtr);
        let delta_norm: f64 = delta.iter().map(|d| d * d).sum::<f64>().sqrt();
        if delta_norm < config.convergence_tol { break; }

        c.w += delta[0]; c.x += delta[1]; c.y += delta[2]; c.z += delta[3];
    }

    c
}

/// Turn a `c` parameter into gauge-normalized QB weights `wᵢ = c*Pᵢ + 1`, with
/// `w₀` divided out so the first weight is the identity.
pub fn make_weights_from_c(c: Quat, cp: &[Quat; 3]) -> [Quat; 3] {
    let w0 = c * cp[0] + Quat::ONE;
    let w1 = c * cp[1] + Quat::ONE;
    let w2 = c * cp[2] + Quat::ONE;
    let w0_inv = w0.inv();
    [Quat::ONE, w1 * w0_inv, w2 * w0_inv]
}

/// Build a QB patch through `corner_positions` whose curvature best matches the
/// given samples. Works on surfaces that are not Möbius images of a plane — the
/// fit is then an approximation rather than a recovery.
pub fn fit_patch_from_samples(
    corner_positions: [[f64; 3]; 3],
    samples: &[[f64; 3]],
    sample_bary: &[[f64; 3]],
    sample_normals: &[[f64; 3]],
    config: &CEstimatorConfig,
) -> QBTriPatch {
    let cp = [
        Quat::from_point(corner_positions[0][0], corner_positions[0][1], corner_positions[0][2]),
        Quat::from_point(corner_positions[1][0], corner_positions[1][1], corner_positions[1][2]),
        Quat::from_point(corner_positions[2][0], corner_positions[2][1], corner_positions[2][2]),
    ];

    let c = estimate_c_parameter(&corner_positions, samples, sample_bary, sample_normals, config);
    let weights = make_weights_from_c(c, &cp);
    QBTriPatch::new(cp, weights)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::roundtrip::{measure_recovery_error, tessellate_patch};
    use quilting_core::quaternion::Mobius;

    fn as_quats(cp: &[[f64; 3]; 3]) -> [Quat; 3] {
        [
            Quat::from_point(cp[0][0], cp[0][1], cp[0][2]),
            Quat::from_point(cp[1][0], cp[1][1], cp[1][2]),
            Quat::from_point(cp[2][0], cp[2][1], cp[2][2]),
        ]
    }

    /// Quantitative c-recovery: build a patch whose weights come from a KNOWN c,
    /// tessellate it, and check the estimator gets that c back.
    ///
    /// Ground truth is exact here: with `wᵢ = c*Pᵢ + 1` the QB surface really is
    /// the Möbius image of the control triangle, so the model is well-specified
    /// and the residual goes to (numerical) zero at the true `c`.
    #[test]
    fn test_recovers_known_c() {
        let corners = [[0.5, 0.0, 2.0], [0.0, 0.5, 2.0], [-0.5, 0.0, 2.0]];
        let cpq = as_quats(&corners);

        // The shipped regularization (0.01) visibly biases c toward zero, so use a
        // token penalty: enough to keep the solve out of the large-|c| valley,
        // small enough that recovery is essentially exact.
        let cfg = CEstimatorConfig { regularization: 1e-6, ..Default::default() };

        for c_true in [
            Quat::new(0.15, -0.08, 0.05, 0.11),
            Quat::new(0.0, 0.1, 0.0, 0.0),
            Quat::new(0.02, -0.01, 0.01, 0.0),
        ] {
            let truth = QBTriPatch::new(cpq, make_weights_from_c(c_true, &cpq));
            let tess = tessellate_patch(&truth, 12);
            let c_est =
                estimate_c_parameter(&corners, &tess.positions, &tess.bary, &tess.normals, &cfg);

            assert!((c_est - c_true).norm() < 1e-4,
                "c not recovered: true = {:?}, est = {:?}", c_true, c_est);

            let fitted = QBTriPatch::new(cpq, make_weights_from_c(c_est, &cpq));
            let err = measure_recovery_error(&truth, &fitted, 16);
            assert!(err.rms_position < 1e-6,
                "surface not recovered for c = {:?}, rms = {:.3e}", c_true, err.rms_position);
            assert!(err.weight_errors[1] < 1e-3 && err.weight_errors[2] < 1e-3,
                "weights not recovered for c = {:?}, errors = {:?}", c_true, err.weight_errors);
        }
    }

    /// The shipped default trades accuracy for stability. It should still land the
    /// surface within a small fraction of the patch size — but do not expect it to
    /// return the generating `c`, because the |c|² penalty pulls it toward zero.
    #[test]
    fn test_default_config_is_accurate_enough_but_biased() {
        let corners = [[0.5, 0.0, 2.0], [0.0, 0.5, 2.0], [-0.5, 0.0, 2.0]];
        let cpq = as_quats(&corners);
        let c_true = Quat::new(0.02, -0.01, 0.01, 0.0);

        let truth = QBTriPatch::new(cpq, make_weights_from_c(c_true, &cpq));
        let tess = tessellate_patch(&truth, 12);
        let c_est = estimate_c_parameter(
            &corners, &tess.positions, &tess.bary, &tess.normals, &Default::default());

        let fitted = QBTriPatch::new(cpq, make_weights_from_c(c_est, &cpq));
        let err = measure_recovery_error(&truth, &fitted, 16);
        assert!(err.rms_position < 1e-3,
            "default tuning should still track the surface, rms = {:.3e}", err.rms_position);
        assert!(c_est.norm() <= c_true.norm() + 1e-9,
            "the |c|² penalty should shrink c, not grow it: {:?} vs {:?}", c_est, c_true);
    }

    /// An inverted patch is a Möbius image, but NOT one this estimator can
    /// reproduce exactly, and it is worth being precise about why.
    ///
    /// The true weights of the image are `wᵢ = c*Fᵢ + d` in terms of the *flat
    /// preimage* corners Fᵢ. Having only the mesh, we reference the curved
    /// corners instead and search `wᵢ = c*Pᵢ + 1` — a different 4-parameter
    /// family that merely contains a good approximation of the target. So the
    /// invariant here is "much better than flat", not "exact".
    #[test]
    fn test_approximates_inversion_far_better_than_flat() {
        let flat = QBTriPatch::flat([0.5, 0.0, 2.0], [0.0, 0.5, 2.0], [-0.5, 0.0, 2.0]);
        let truth = flat.transform(&Mobius::inversion());
        let tess = tessellate_patch(&truth, 12);
        let corners = [
            truth.positions[0].to_point(),
            truth.positions[1].to_point(),
            truth.positions[2].to_point(),
        ];

        let cfg = CEstimatorConfig { regularization: 1e-6, ..Default::default() };
        let fitted = fit_patch_from_samples(corners, &tess.positions, &tess.bary, &tess.normals, &cfg);
        let err = measure_recovery_error(&truth, &fitted, 16);

        let flat_through_corners =
            QBTriPatch::new(truth.positions, [Quat::ONE, Quat::ONE, Quat::ONE]);
        let flat_err = measure_recovery_error(&truth, &flat_through_corners, 16);

        assert!(err.rms_position < flat_err.rms_position / 10.0,
            "c-fit should beat the flat triangle by an order of magnitude: {:.3e} vs {:.3e}",
            err.rms_position, flat_err.rms_position);
        assert!(err.rms_position < 1e-3,
            "c-fit should track the inverted surface closely, rms = {:.3e}", err.rms_position);
    }

    /// The normal weight must be applied identically when building residuals and
    /// when building the finite-difference Jacobian. Changing it should change
    /// the answer (it is genuinely wired in) but never destabilize the solve.
    #[test]
    fn test_normal_weight_is_consistently_applied() {
        let corners = [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]];
        let n = 6;
        let (mut positions, mut bary, mut normals) = (Vec::new(), Vec::new(), Vec::new());
        for i in 0..=n {
            for j in 0..=(n - i) {
                let u = i as f64 / n as f64;
                let v = j as f64 / n as f64;
                let w = 1.0 - u - v;
                let p = [w, u, v];
                let r = (p[0] * p[0] + p[1] * p[1] + p[2] * p[2]).sqrt();
                let s = [p[0] / r, p[1] / r, p[2] / r];
                positions.push(s);
                normals.push(s); // unit sphere: normal = position
                bary.push([w, u, v]);
            }
        }

        let base = CEstimatorConfig::default();
        let no_normals = CEstimatorConfig { normal_weight: 0.0, ..Default::default() };
        let c_a = estimate_c_parameter(&corners, &positions, &bary, &normals, &base);
        let c_b = estimate_c_parameter(&corners, &positions, &bary, &normals, &no_normals);

        for c in [c_a, c_b] {
            assert!(c.w.is_finite() && c.x.is_finite() && c.y.is_finite() && c.z.is_finite());
        }
        assert!((c_a - c_b).norm() > 1e-9, "normal_weight should actually affect the solve");
    }
}
